import { chromium } from "playwright-core";
const dir = process.argv[2];
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 393, height: 852 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => m.type() === "error" && errors.push(m.text()));
await page.goto("http://localhost:3000/chat", { waitUntil: "networkidle" });
await page.waitForTimeout(800);
let n = 0;
const snap = async () => page.screenshot({ path: `${dir}/c${n++}.png` });
const click = async (t) => { await page.getByText(t, { exact: true }).first().click(); await page.waitForTimeout(1600); await snap(); };
await snap();
await click("Still stressed");
await click("I can’t make myself start");
await click("Yes, that’s me");
await click("Make a recovery plan");
if (errors.length) console.log("ERRORS:\n" + errors.join("\n"));
await browser.close();
